Repository taisei-project/taisei, pull requests merged in 2018-05, with the labels that each got.

#118 [WIP] Projectile prototypes system
  src/boss.c
  src/enemy.c
  src/enemy.h
  src/global.h
  src/item.c
  src/laser.c
  src/meson.build
  src/player.c
  src/plrmodes/marisa.c
  src/plrmodes/marisa_a.c
  src/plrmodes/marisa_b.c
  src/plrmodes/youmu.c
  src/plrmodes/youmu.h
  src/plrmodes/youmu_a.c
  src/plrmodes/youmu_b.c
  src/projectile.c
  src/projectile.h
  src/projectile_prototypes.c
  src/projectile_prototypes/all.inc.h
  src/projectile_prototypes/basic.inc.h
  src/stages/stage1_events.c
  src/stages/stage2_events.c
  src/stages/stage3_events.c
  src/stages/stage4_events.c
  src/stages/stage5_events.c
  src/stages/stage6_events.c
Labels: engine, help wanted

#122 Improve (totally rewrite) projectile collision detection and graze mechanics
  src/laser.c
  src/laser.h
  src/player.c
  src/player.h
  src/projectile.c
  src/projectile.h
  src/projectile_prototypes.c
  src/projectile_prototypes/all.inc.h
  src/projectile_prototypes/basic.inc.h
  src/projectile_prototypes/player.inc.h
  src/stagedraw.c
  src/stages/stage1_events.c
  src/stages/stage3_events.c
  src/stages/stage4_events.c
  src/stages/stage5_events.c
  src/stages/stage6_events.c
  src/util.c
  src/util.h
Labels: bug, engine, gameplay

#119 Post-battle revision for Marisa
  src/dialog/marisa.c
Labels: content

#120 Post-battle revision for Reimu
  src/dialog/reimu.c
Labels: content

#121 Post-battle revision for Youmu
  src/dialog/youmu.c
Labels: content

#123 Post-battle dialogue
  src/dialog/marisa.c
  src/dialog/reimu.c
  src/dialog/youmu.c
Labels: content

#125 Threading improvements
  src/audio_common.c
  src/dialog/reimu.h
  src/hashtable.c
  src/hashtable.h
  src/hirestime.c
  src/log.h
  src/main.c
  src/meson.build
  src/resource/resource.c
  src/resource/resource.h
  src/taskmanager.c
  src/taskmanager.h
  src/util/crap.c
  src/vfs/public.c
  src/video.c
Labels: engine
