Repository taisei-project/taisei, pull requests merged in 2020-03, with the labels that each got.

#199 Coroutinize ReimuA
  src/enemy.c
  src/enemy.h
  src/player.c
  src/player.h
  src/plrmodes/reimu_a.c
Labels: gameplay, refactor

#200 Implement Robin Hood hashing
  meson_options.txt
  src/hashtable.c
  src/hashtable.h
  src/hashtable.inc.h
  src/hashtable_predefs.inc.h
  src/main.c
  src/meson.build
  src/renderer/api.c
  src/renderer/api.h
  src/renderer/common/backend.h
  src/renderer/gl33/shader_program.c
  src/renderer/gl33/shader_program.h
  src/renderer/null/null.c
  src/resource/font.c
  src/resource/font.h
  src/resource/resource.c
  src/resource/resource.h
  src/resource/sprite.c
  src/resource/sprite.h
  src/resource/texture.c
  src/resource/texture.h
  src/util.h
  src/util/compat.h
  src/util/meson.build
  src/util/sse42.c
  src/util/sse42.h
  src/util/stringops.c
  src/util/stringops.h
Labels: engine, performance

#197 [WIP] Stage 3 coroutinize
  src/stages/stage3.c
  src/stages/stage3_events.c
  src/stages/stage3_events.h
Labels: gameplay, refactor

#204 Video resolution improvements/high-DPI quirks
  misc/Info.plist.in
  src/menu/options.c
  src/renderer/gl33/gl33.c
  src/video.c
  src/video.h
Labels: engine, qol
