Repository taisei-project/taisei, pull requests merged in 2020-12, with the labels that each got.

#229 Stage 2 revamp
  src/common_tasks.c
  src/common_tasks.h
  src/stages/stage1/nonspells/nonspells.h
  src/stages/stage2/meson.build
  src/stages/stage2/nonspells/boss_nonspell_1.c
  src/stages/stage2/nonspells/boss_nonspell_2.c
  src/stages/stage2/nonspells/boss_nonspell_3.c
  src/stages/stage2/nonspells/midboss_nonspell_1.c
  src/stages/stage2/nonspells/nonspells.h
  src/stages/stage2/spells/amulet_of_harm.c
  src/stages/stage2/spells/bad_pick.c
  src/stages/stage2/spells/monty_hall_danmaku.c
  src/stages/stage2/spells/spells.h
  src/stages/stage2/spells/wheel_of_fortune.c
  src/stages/stage2/stage2.c
  src/stages/stage2/timeline.c
  src/stages/stage2/timeline.h
Labels: gameplay, refactor

#271 Reduce compile-time noise with `libzip` and `clang`
  src/vfs/zipfile_impl.h
Labels: build

#272 Fix build warnings for `clang`
  src/audio/stream/stream_opus.c
  src/log.c
  src/pixmap/loaders/loader_png.c
Labels: build

#273 More compiler warning fixes
  README.rst
  meson.build
  src/coroutine.c
  src/plrmodes/marisa_b.c
  src/plrmodes/reimu_a.c
  src/plrmodes/youmu_b.c
  src/resource/animation.c
  src/stages/stage1/timeline.c
  src/stages/stage2/spells/amulet_of_harm.c
  src/stages/stage2/timeline.c
  src/util/strbuf.c
  src/vfs/platform_paths/meson.build
Labels: bug, build, code health
