Repository taisei-project/taisei, pull requests merged in 2020-05, with the labels that each got.

#227 Separate StageInfo-related APIs from game-stage code
  src/boss.c
  src/cli.c
  src/global.h
  src/main.c
  src/menu/common.c
  src/menu/mainmenu.c
  src/menu/replayview.c
  src/menu/spellpractice.c
  src/menu/stagepractice.c
  src/menu/stageselect.c
  src/meson.build
  src/progress.c
  src/replay.c
  src/stage.c
  src/stage.h
  src/stageinfo.c
  src/stageinfo.h
  src/stages/corotest.h
  src/stages/dpstest.h
  src/stages/extra.c
  src/stages/extra.h
  src/stages/stage1.h
  src/stages/stage1_events.c
  src/stages/stage2.h
  src/stages/stage2_events.c
  src/stages/stage3.h
  src/stages/stage3_events.c
  src/stages/stage4.h
  src/stages/stage4_events.c
  src/stages/stage5.h
  src/stages/stage6.h
Labels: engine, refactor

#225 Revamp screen shake system
  src/boss.c
  src/global.h
  src/plrmodes/marisa_a.c
  src/plrmodes/marisa_b.c
  src/plrmodes/reimu_a.c
  src/plrmodes/reimu_b.c
  src/stage.c
  src/stage.h
  src/stagedraw.c
  src/stages/stage5_events.c
  src/stages/stage6_events.c
Labels: gameplay, refactor

#228 Split stage1 into multiple files
  src/stageinfo.c
  src/stages/meson.build
  src/stages/stage1/background_anim.c
  src/stages/stage1/background_anim.h
  src/stages/stage1/cirno.c
  src/stages/stage1/cirno.h
  src/stages/stage1/draw.c
  src/stages/stage1/draw.h
  src/stages/stage1/meson.build
  src/stages/stage1/misc.c
  src/stages/stage1/misc.h
  src/stages/stage1/nonspells/boss_nonspell_1.c
  src/stages/stage1/nonspells/boss_nonspell_2.c
  src/stages/stage1/nonspells/midboss_nonspell_1.c
  src/stages/stage1/nonspells/nonspells.h
  src/stages/stage1/spells/benchmark.c
  src/stages/stage1/spells/crystal_blizzard.c
  src/stages/stage1/spells/crystal_rain.c
  src/stages/stage1/spells/icicle_cascade.c
  src/stages/stage1/spells/perfect_freeze.c
  src/stages/stage1/spells/snow_halation.c
  src/stages/stage1/spells/spells.h
  src/stages/stage1/stage1.c
  src/stages/stage1/stage1.h
  src/stages/stage1/timeline.c
  src/stages/stage1/timeline.h
  src/stages/stage1_events.c
Labels: refactor

#230 [spoilers] Small edits to the endings
  src/ending.c
Labels: content, spoilers

#233 [spoilers] Slight EX boss dialogue tweaks
  src/dialog/marisa.c
  src/dialog/reimu.c
  src/dialog/youmu.c
Labels: content, spoilers
