Repository taisei-project/taisei, pull requests merged in 2020-02, with the labels that each got.

#187 OpenGL ES 2.0 support
  README.rst
  doc/ENVIRON.rst
  resources/00-taisei.pkgdir/shader/boss_death.frag.glsl
  resources/00-taisei.pkgdir/shader/fxaa.frag.glsl
  resources/00-taisei.pkgdir/shader/fxaa.vert.glsl
  resources/00-taisei.pkgdir/shader/interface/fxaa.glslh
  resources/00-taisei.pkgdir/shader/laser_generic.vert.glsl
  resources/00-taisei.pkgdir/shader/lasers/common.vert.glslh
  resources/00-taisei.pkgdir/shader/lasers/vertex_pos.glslh
  resources/00-taisei.pkgdir/shader/lib/defs.glslh
  resources/00-taisei.pkgdir/shader/lib/fxaa.glslh
  resources/00-taisei.pkgdir/shader/lib/legacy_compat.glslh
  resources/00-taisei.pkgdir/shader/player_death.frag.glsl
  src/boss.c
  src/laser.c
  src/player.c
  src/renderer/api.c
  src/renderer/api.h
  src/renderer/common/shaderlib/cache.c
  src/renderer/common/shaderlib/lang_spirv.c
  src/renderer/common/shaderlib/lang_spirv_aux.c
  src/renderer/gl33/shader_program.c
  src/renderer/gl33/shader_program.h
  src/renderer/glcommon/debug.c
  src/renderer/glcommon/texture.c
  src/renderer/gles20/gles20.c
  src/renderer/glescommon/texture.c
  src/resource/shader_object.c
  src/stages/stage1.c
  src/stages/stage2.c
  src/stages/stage3.c
  src/stages/stage4.c
  src/stages/stage5.c
  src/stages/stage6.c
Labels: engine, rendering

#189 sin() broken on values over 10,000 on Intel (shaders)
  resources/00-taisei.pkgdir/shader/lib/.util.glslh.swp
  resources/00-taisei.pkgdir/shader/lib/util.glslh
  resources/00-taisei.pkgdir/shader/stage1_water.frag.glsl
Labels: driver issue, rendering

#188 Workaround for macOS AMD performance issues
  src/renderer/gl33/gl33.c
  src/renderer/gl33/gl33.h
  src/renderer/gl33/shader_program.c
  src/renderer/gl33/texture.c
  src/renderer/glcommon/opengl.c
  src/renderer/glcommon/opengl.h
Labels: driver issue, macOS, rendering

#190 OpenGL ES 3.0/ANGLE support on macOS
  meson.build
  meson_options.txt
  misc/Info.plist.in
  misc/meson.build
  src/meson.build
  src/renderer/glcommon/opengl.c
  src/renderer/glescommon/gles.c
  src/renderer/meson.build
Labels: macOS

#192 New (themed) difficulty/shot mode descriptions
  .gitignore
  atlas/common_ui/difficulty/easy.png
  atlas/common_ui/difficulty/easy.webp
  atlas/common_ui/difficulty/hard.png
  atlas/common_ui/difficulty/hard.webp
  atlas/common_ui/difficulty/lunatic.png
  atlas/common_ui/difficulty/lunatic.webp
  atlas/common_ui/difficulty/normal.png
  atlas/common_ui/difficulty/normal.webp
  doc/STORY.txt
  resources/00-taisei.pkgdir/gfx/atlas_common_ui_0.webp
  resources/00-taisei.pkgdir/gfx/boss_indicator.spr
  resources/00-taisei.pkgdir/gfx/difficulty/easy.spr
  resources/00-taisei.pkgdir/gfx/difficulty/hard.spr
  resources/00-taisei.pkgdir/gfx/difficulty/lunatic.spr
  resources/00-taisei.pkgdir/gfx/difficulty/normal.spr
  resources/00-taisei.pkgdir/gfx/hud/heart.spr
  resources/00-taisei.pkgdir/gfx/hud/star.spr
  resources/00-taisei.pkgdir/gfx/menu/arrow.spr
  resources/00-taisei.pkgdir/gfx/menu/logo.spr
  resources/00-taisei.pkgdir/gfx/spell.spr
  resources/00-taisei.pkgdir/gfx/star.spr
  src/menu/difficultyselect.c
  src/plrmodes/marisa.c
  src/plrmodes/marisa_a.c
  src/plrmodes/marisa_b.c
  src/plrmodes/reimu.c
  src/plrmodes/reimu_a.c
  src/plrmodes/reimu_b.c
  src/plrmodes/youmu.c
  src/plrmodes/youmu_a.c
  src/plrmodes/youmu_b.c
Labels: content
