Repository taisei-project/taisei, pull requests merged in 2021-05, with the labels that each got.

#294 events: reduce processing overhead
  src/dynarray.c
  src/events.c
  src/events.h
  src/gamepad.c
  src/stage.c
Labels: engine, performance

#295 Add -lwebgl.js to fix macOS Emscripten build error
  src/meson.build
Labels: build, macOS

#286 Windows test builds, cleanup of CI
  .github/workflows/main.yml
  misc/ci/linux-x86_64-build-test-ci.ini
  misc/ci/macos-x86_64-build-test-ci.ini
  misc/ci/tests/test-replay.tsr
  misc/ci/windows-llvm_mingw-x86_64-build-test-ci.ini
Labels: build

#296 Emscripten CI test builds
  .github/workflows/main.yml
  misc/ci/emscripten-build-test-ci.ini
  misc/ci/linux-x86_64-build-test-ci.ini
  misc/ci/macos-x86_64-build-test-ci.ini
  misc/ci/windows-llvm_mingw-x86_64-build-test-ci.ini
Labels: ci

#299 Switch CI test builds
  .github/workflows/main.yml
  switch/crossfile.sh
Labels: ci
