Repository taisei-project/taisei, pull requests merged in 2021-07, with the labels that each got.

#304 Bump `emsdk` to `2.0.25`, rework separate check for `tot`
  .github/workflows/emscripten-experimental.yml
  .github/workflows/main.yml
  resources/meson.build
  src/meson.build
Labels: ci, emscripten

#310 stage3: restructure into a folder-based layout
  src/stageinfo.c
  src/stages/meson.build
  src/stages/stage3.c
  src/stages/stage3/background_anim.c
  src/stages/stage3/background_anim.h
  src/stages/stage3/draw.c
  src/stages/stage3/draw.h
  src/stages/stage3/meson.build
  src/stages/stage3/nonspells/boss_nonspells.c
  src/stages/stage3/nonspells/midboss_nonspell_1.c
  src/stages/stage3/nonspells/nonspells.h
  src/stages/stage3/scuttle.c
  src/stages/stage3/scuttle.h
  src/stages/stage3/spells/deadly_dance.c
  src/stages/stage3/spells/firefly_storm.c
  src/stages/stage3/spells/light_singularity.c
  src/stages/stage3/spells/moonlight_rocket.c
  src/stages/stage3/spells/night_ignite.c
  src/stages/stage3/spells/spells.h
  src/stages/stage3/stage3.c
  src/stages/stage3/stage3.h
  src/stages/stage3/timeline.c
  src/stages/stage3/timeline.h
  src/stages/stage3/wriggle.c
  src/stages/stage3/wriggle.h
  src/stages/stage3_events.c
Labels: refactor

#303 Improved README.
  README.rst
Labels: documentation
